services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/json:/app/json
      - ./backend/svgs:/app/svgs
    environment:
      - GO_ENV=production
    command: ["./main"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=http://backend:8080
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://backend:8080
    depends_on:
      - backend