services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recipe-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/json:/app/json
    environment:
      - GO_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: recipe-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/next.config.mjs
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend/tailwind.config.ts
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
    restart: unless-stopped